

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


name: terraform Workflow

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'


jobs:
  terraform-action:
    runs-on: ubuntu-latest
    steps:
      - name: venkatamutyala-test-action1              
        uses: venkatamutyala/test-action1@main
