

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


name: terraform Workflow new

on:
  push:
    branches:
      - main
  pull_request:


jobs:
  terraform-action:
    runs-on: ubuntu-latest
    steps:
      - name: venkatamutyala-test-action1              
        uses: venkatamutyala/test-action1@main
        with:
          backend_config: |
            access_key=${{ secrets.TF_S3_ACCESS_KEY_ID }}
            secret_key=${{ secrets.TF_S3_ACCESS_KEY_SECRET }}
            
