env:
  TERRAFORM_ACTIONS_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  OPENTOFU_VERSION: "1.6.2"
  # more provider environment variables can be set here


name: OpenTofu CD

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform-action:
    runs-on: ubuntu-latest
    concurrency:
      group: limit-concurrency-do-not-remove-this
      cancel-in-progress: false
    steps:
      - name: OpenTofu CD              
        uses: GlueOps/github-actions-opentofu-continuous-delivery@main
        with:
          backend_config: |
            access_key=${{ secrets.TF_S3_ACCESS_KEY_ID }}
            secret_key=${{ secrets.TF_S3_ACCESS_KEY_SECRET }}
            bucket=venkata-test-bucket
            region=us-west-2
            key=${{ github.repository }}/terraform.tfstate
