name: terraform Workflow

on:
  issue_comment:
    types: [created]

jobs:
  prepare-matrix:
    if: >-
      contains(github.event.comment.body, 'terraform plan') ||
      contains(github.event.comment.body, 'terraform apply') ||
      contains(github.event.comment.body, 'terraform yolo')
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Find Modified Terraform Directories
        id: set-matrix
        run: |
          FILES=$(git diff --name-only HEAD~1..HEAD | grep '\.tf$' || echo "")
          DIRS=()
          for file in $FILES; do
            DIR=$(dirname "$file")
            if [[ ! " ${DIRS[@]} " =~ " ${DIR} " ]]; then
              DIRS+=("$DIR")
            fi
          done
          JSON_FMT=$(IFS=,; echo "[\"${DIRS[*]}\"]" | sed 's/ /", "/g')
          echo "::set-output name=matrix::{\"include\":$JSON_FMT}"

  terraform-plan:
    needs: prepare-matrix
    if: contains(github.event.comment.body, 'terraform plan')
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.prepare-matrix.outputs.matrix)}}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Terraform Plan
        uses: dflook/terraform-plan@v1
        with:
          path: ${{ matrix.include }}
  
  # Additional jobs for 'terraform apply', 'terraform yolo', etc. can be added similarly
