name: terraform Workflow

on:
  issue_comment:
    types: [created]

jobs:
  prepare-matrix:
    if: >-
      contains(github.event.comment.body, 'terraform plan') ||
      contains(github.event.comment.body, 'terraform apply') ||
      contains(github.event.comment.body, 'terraform yolo')
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}



      - name: Find Modified Terraform Directories
        id: set-matrix
        run: |
          echo "Fetching all branches..."
          git fetch --all
          git branch --all
          echo "Current Branch: $(git branch --show-current) and current sha: $(git rev-parse `git branch --show-current`)"




          echo "Listing all modified files..."
          MODIFIED_FILES=$(git diff --name-only origin/main...$(git rev-parse `git branch --show-current`))
          echo "Modified Files: ${MODIFIED_FILES}"

          echo "Extracting directory paths..."
          DIRS=()
          for file in $MODIFIED_FILES; do
            DIR=$(dirname "$file")
            DIRS+=("$DIR")
          done
          UNIQUE_DIRS=($(echo "${DIRS[@]}" | tr ' ' '\n' | sort -u | tr '\n' ' '))

          echo "Found directories: ${UNIQUE_DIRS[@]}"
          JSON_FMT=$(IFS=,; echo "[{\"directory\":\"${UNIQUE_DIRS[*]}\"}]" | sed 's/ /\", \"directory\":\"/g')
          echo $JSON_FMT
          echo "::set-output name=matrix::{\"include\":$JSON_FMT}"


  terraform-plan:
    needs: prepare-matrix
    if: >-
      contains(github.event.comment.body, 'terraform plan') &&
      needs.prepare-matrix.outputs.matrix != '{}'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.prepare-matrix.outputs.matrix.include)}}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Terraform Plan
        run: |
          echo "Running Terraform Plan for directory: ${{ matrix.directory }}"
          # Replace with actual Terraform command
          # Example: terraform plan -path=${{ matrix.directory }}
