

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


name: terraform Workflow

on:
  push:
  pull_request:
    - created


jobs:
  terraform-action:
    runs-on: ubuntu-latest
    steps:
      - name: venkatamutyala-test-action1              
        uses: venkatamutyala/test-action1@main
