name: terraform Workflow

on:
  issue_comment:
    types: [created]

jobs:
  prepare-matrix:
    if: >-
      contains(github.event.comment.body, 'terraform plan') ||
      contains(github.event.comment.body, 'terraform apply') ||
      contains(github.event.comment.body, 'terraform yolo')
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Find Modified Terraform Directories
        id: set-matrix
        run: |
          echo "Fetching repository history..."
          git fetch --no-tags --depth=1 origin +refs/heads/*:refs/remotes/origin/*
          
          echo "Looking for modified .tf files..."
          BASE_REF=${{ github.base_ref }}
          HEAD_REF=${{ github.head_ref }}
          if [ -z "$BASE_REF" ] || [ -z "$HEAD_REF" ]; then
            BASE_REF=main
            HEAD_REF=HEAD
          fi

          FILES=$(git diff --name-only "refs/remotes/origin/$BASE_REF...$HEAD_REF" | grep '\.tf$' || echo "")
          DIRS=()
          for file in $FILES; do
            DIR=$(dirname "$file")
            if [[ ! " ${DIRS[@]} " =~ " ${DIR} " ]]; then
              DIRS+=("$DIR")
            fi
          done
          echo "Found directories: ${DIRS[@]}"
          if [ ${#DIRS[@]} -eq 0 ]; then
            echo "No Terraform files modified."
            echo "::set-output name=matrix::{}"
          else
            JSON_FMT=$(IFS=,; echo "[{\"directory\":\"${DIRS[*]}\"}]" | sed 's/ /\", \"directory\":\"/g')
            echo "Matrix JSON: $JSON_FMT"
            echo "::set-output name=matrix::{\"include\":$JSON_FMT}"
          fi

  terraform-plan:
    needs: prepare-matrix
    if: >-
      contains(github.event.comment.body, 'terraform plan') &&
      needs.prepare-matrix.outputs.matrix != '{}'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.prepare-matrix.outputs.matrix.include)}}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Terraform Plan
        run: |
          echo "Running Terraform Plan for directory: ${{ matrix.directory }}"
          # Replace with actual Terraform command
          # Example: terraform plan -path=${{ matrix.directory }}
